### PR TITLE
Add dotenv to gulp and some small fixes, fixes #18

### LINKED ISSUE #18: use .env in gulpfile for browsersync
dotenv = require('dotenv').load();

### PR DESCRIPTION
**Pull request by simonpeters**

### CODE REVIEW

File: gulp/tasks/bower.js [hunk 1]
```diff
@@ -12,23 +12,25 @@ module.exports = function (gulp, paths, plugins, options) {
             paths: {bowerDirectory: paths.BOWER_PATH}
         });
 
+        console.log(mainFiles);
```
Comment (VincentPeters) [inline gulp/tasks/bower.js]: console log
